apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hmi
  template:
    metadata:
      labels:
        app: hmi
    spec:
      containers:
        - name: hmi
          image: australia-southeast2-docker.pkg.dev/sit-23t1-project-echo-25288b9/project-echo/rb-echo-hmi:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hmi-env
