
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
      - name: iot-simulator
        image: ts-simulator:latest #for development, use <registry-name>/ts-simulator:latest
        restartPolicy: Always
