apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-env
data:
  DB_USER: modelUser
  DB_USER_PASS: EchoNetAccess2023
  DB_ROOT_USER: root
  DB_ROOT_USER_PASS: root_password
  REDIS_HOST: value
  DB_HOST: value
  API_HOST: value
