apiVersion: v1
kind: ConfigMap
metadata:
  name: hmi-env
data:
  DB_USER: modelUser
  DB_USER_PASS: EchoNetAccess2023
  DB_ROOT_USER: root
  DB_ROOT_USER_PASS: root_password
  REDIS_HOST: echo-redis
  DB_HOST: mongodb-service
  API_HOST: api-service
