name: panns_mobilenetv2
norm_choice: swap_rms_norm
params:
  model_name: "panns_mobilenetv2"
  pretrained: true
  num_classes: ${data.num_classes}
  use_qat: true
  trainable_blocks: -1
  use_arcface: true

