apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-echo
  namespace: project-echo
  annotations:
    networking.gke.io/managed-certificates: project-echo-dev-cert
spec:
  rules:
    - host: dev.echo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hmi
                port:
                  name: http
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
