apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: project-echo
  annotations:
    iam.gke.io/gcp-service-account: dev-api@sit-23t1-project-echo-25288b9.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine
  namespace: project-echo
  annotations:
    iam.gke.io/gcp-service-account: dev-engine@sit-23t1-project-echo-25288b9.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hmi
  namespace: project-echo
  annotations:
    iam.gke.io/gcp-service-account: dev-hmi@sit-23t1-project-echo-25288b9.iam.gserviceaccount.com
