apiVersion: v1
kind: Service
metadata:
  name: engine
  namespace: project-echo
  labels:
    app.kubernetes.io/name: engine
    app.kubernetes.io/component: inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: engine
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
