apiVersion: v1
kind: Service
metadata:
  name: hmi
  namespace: project-echo
  labels:
    app.kubernetes.io/name: hmi
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hmi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
