apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: project-echo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: datastore
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
      protocol: TCP
