apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: api-secrets
      namespace: project-echo
      annotations:
        secret.kubernetes.io/managed-by: external
    type: Opaque
    stringData:
      MONGO_URI: ""
      REDIS_URL: ""
  - apiVersion: v1
    kind: Secret
    metadata:
      name: engine-secrets
      namespace: project-echo
      annotations:
        secret.kubernetes.io/managed-by: external
    type: Opaque
    stringData:
      MODEL_BUCKET: ""
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mongo-secrets
      namespace: project-echo
      annotations:
        secret.kubernetes.io/managed-by: external
    type: Opaque
    stringData:
      ROOT_USERNAME: ""
      ROOT_PASSWORD: ""
  - apiVersion: v1
    kind: Secret
    metadata:
      name: redis-secrets
      namespace: project-echo
      annotations:
        secret.kubernetes.io/managed-by: external
    type: Opaque
    stringData:
      REDIS_PASSWORD: ""
