apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  continue: ""
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: api
      namespace: project-echo
      annotations:
        iam.gke.io/gcp-service-account: placeholder-api@PROJECT_ID.iam.gserviceaccount.com
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: engine
      namespace: project-echo
      annotations:
        iam.gke.io/gcp-service-account: placeholder-engine@PROJECT_ID.iam.gserviceaccount.com
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: hmi
      namespace: project-echo
      annotations:
        iam.gke.io/gcp-service-account: placeholder-hmi@PROJECT_ID.iam.gserviceaccount.com
